site_name: Betting Feed Documentation
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Autenticazione: authentication.md
  - API REST: rest-api.md
  - RabbitMQ Feed: rabbitmq.md
  - Esempi: examples.md
  - API Reference: swagger.md

plugins:
  - search
  - swagger-ui-tag
